# Generated by Django 5.0.1 on 2024-01-11 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quality",
            new_name="quantity",
        ),
    ]
